env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:storybook/recommended
  - standard-with-typescript
  - plugin:react/jsx-runtime
  - prettier
overrides: []
settings:
  react:
    version: detect
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
  project:
    - ./tsconfig.json
plugins:
  - react
rules:
  "@typescript-eslint/consistent-type-assertions":
    - error
    - assertionStyle: as
      objectLiteralTypeAssertions: allow-as-parameter
  "@typescript-eslint/consistent-type-definitions": off
  # "@typescript-eslint/consistent-type-imports": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-confusing-void-expression": off
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-misused-promises":
    - error
    - checksVoidReturn: false
  "@typescript-eslint/triple-slash-reference":
    - error
    - types: prefer-import
  no-console:
    - error
    - allow:
        - debug
        - error
        - info
        - trace
        - warn
