name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        shardTotal: [9]
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install unzip
        run: |
          apt-get update
          apt-get install unzip

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Use cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Playwright tests
        run: bun run playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          RUNTIME_FIREBASE_API_KEY: ${{ secrets.RUNTIME_FIREBASE_API_KEY }}
          RUNTIME_FIREBASE_AUTH_DOMAIN: ${{ secrets.RUNTIME_FIREBASE_AUTH_DOMAIN }}
          RUNTIME_FIREBASE_PROJECT_ID: ${{ secrets.RUNTIME_FIREBASE_PROJECT_ID }}
          RUNTIME_FIREBASE_STORAGE_BUCKET: ${{ secrets.RUNTIME_FIREBASE_STORAGE_BUCKET }}
          RUNTIME_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.RUNTIME_FIREBASE_MESSAGING_SENDER_ID }}
          RUNTIME_FIREBASE_APP_ID: ${{ secrets.RUNTIME_FIREBASE_APP_ID }}
          GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          GOOGLE_OPT_SECRET: ${{ secrets.GOOGLE_OPT_SECRET }}
          GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
          # Required for firefox
          HOME: /root
      - name: Upload playwright report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 1
